export type Product={slug:string;name:string;category:string;price:number;originalPrice?:number;badges:string[];customizable:boolean;availability:'AVAILABLE'|'LIMITED SLOTS'|'FULLY BOOKED';productionDays:number;description:string;materials:string[];stock:number|null};
export const products:Product[]=[
{slug:'strawberry-milk-clay-charm',name:'Strawberry Milk Clay Charm',category:'Clay charms',price:349,originalPrice:399,badges:['New','Customizable'],customizable:true,availability:'AVAILABLE',productionDays:4,description:'A tiny glossy charm inspired by strawberry milk, hand shaped and sealed.',materials:['air dry clay','varnish','keyring'],stock:12},
{slug:'mini-daisy-forever-flower',name:'Mini Daisy Forever Flower',category:'Forever flowers',price:299,badges:['Best seller'],customizable:false,availability:'LIMITED SLOTS',productionDays:3,description:'A forever daisy stem for desks, hampers and little reminders.',materials:['pipe cleaner','floral tape'],stock:null},
{slug:'custom-bestie-tote',name:'Custom Bestie Tote',category:'Custom totes',price:799,badges:['Customizable'],customizable:true,availability:'AVAILABLE',productionDays:7,description:'A personalized tote with names, doodles, colors and inside jokes.',materials:['canvas tote','fabric paint'],stock:null},
{slug:'birthday-mini-hamper',name:'Birthday Mini Hamper',category:'Birthday hampers',price:999,originalPrice:1199,badges:['Limited edition'],customizable:true,availability:'AVAILABLE',productionDays:6,description:'A packed-with-love mini hamper with handmade details and a message card.',materials:['gift box','paper goods','handmade add-ons'],stock:6},
{slug:'pink-bow-phone-charm',name:'Pink Bow Phone Charm',category:'Phone charms',price:249,badges:['New'],customizable:false,availability:'AVAILABLE',productionDays:2,description:'Soft pink beads, bows and a sweet phone loop.',materials:['beads','cord','bow charm'],stock:20},
{slug:'personalized-memory-magazine',name:'Personalized Memory Magazine',category:'Scrapbook gifts',price:1499,badges:['Customizable','Best seller'],customizable:true,availability:'LIMITED SLOTS',productionDays:10,description:'A magazine-style scrapbook for photos, notes, playlists and stories.',materials:['premium paper','prints','binding'],stock:null},
];
export const categories=['Phone charms','Bag charms','Keychains','Clay charms','Clay stickers','Clay magnets','Forever flowers','Bouquets','Custom totes','Birthday hampers','Friendship gifts','Couple gifts','Scrapbook gifts','Build your own gift'];
export const budgetRanges=[499,799,999,1499,1999,2999];
